### PR TITLE
fix: incorrect pytest plugin entrypoint name

### PR DESCRIPTION
**Pull request by Kache**
Fixes: #71

### CODE REVIEW

**Comment by brycedrennan** [comment]
Nice catch!

**Review by brycedrennan — APPROVED** [review]

**Comment by Kache** [comment]
Was the autoformatter (black) already failing in this manner on master? @brycedrennan can you help with this?

**Comment by brycedrennan** [comment]
Sorry I should have mentioned that failure is unrelated to your changes. I'll handle it.

**Comment by Kache** [comment]
Thanks! Can this get released as 2.1.6? I'm actually facing the pytest plugin entrypoint name collision described in #71.

**Comment by brycedrennan** [comment]
@Kache I've released it as 2.1.6

**Pull request merged**
